### ISSUE TITLE
gjFour not filled?

### ISSUE THREAD

**Issue by davelab6** [itfoundry/kumar#3]
Is the filled `gjFour` glyph correct?

<img width="127" alt="screen shot 2016-04-05 at 23 35 05" src="https://cloud.githubusercontent.com/assets/261579/14305103/1151bd20-fb87-11e5-8c49-e8ecb4c32ee1.png">

It it the only glyph with an outlined part...

**Comment by parimalparmar** [comment]
Hi Dave. That's been corrected! The left diagonal stroke is now same as the right one, filled!
